"""empty message

Revision ID: 42b0650ce90d
Revises: a5cffa318ac2
Create Date: 2025-06-06 00:41:23.842669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0650ce90d'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('altura', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('periodo_rotacion', sa.String(length=100), nullable=False),
    sa.Column('periodo_orbital', sa.String(length=100), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.String(length=50), nullable=False),
    sa.Column('clima', sa.String(length=100), nullable=False),
    sa.Column('gravedad', sa.String(length=100), nullable=False),
    sa.Column('poblacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('fabricante', sa.String(length=120), nullable=False),
    sa.Column('costo_en_creditos', sa.String(length=50), nullable=False),
    sa.Column('longitud', sa.String(length=50), nullable=False),
    sa.Column('tripulacion', sa.String(length=50), nullable=False),
    sa.Column('pasajeros', sa.String(length=50), nullable=False),
    sa.Column('capacidad_de_carga', sa.String(length=50), nullable=False),
    sa.Column('consumibles', sa.String(length=50), nullable=False),
    sa.Column('clase', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('contraseña', sa.String(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('contraseña')
        batch_op.drop_column('correo')
        batch_op.drop_column('nombre')

    op.drop_table('favoritos')
    op.drop_table('vehiculos')
    op.drop_table('planetas')
    op.drop_table('personas')
    # ### end Alembic commands ###
